"""
Stage 2 — INVESTIGATE.

Detection produces a number. Investigation explains it: which signals
actually fired, what they mean in plain language, and — by weighing the
signals against each other — a root-cause narrative of *why* the risk
exists rather than just *that* it exists.

If ANTHROPIC_API_KEY is set in the environment, the root-cause narrative
is generated by Claude from the same structured evidence for a richer,
freer explanation. Without a key, a deterministic template is used, so
the app works fully out of the box.
"""

from __future__ import annotations
import os
from typing import List, Dict, Any, Tuple


def _fmt_money(v: float) -> str:
    return f"₹{v:,.0f}"


def build_evidence(
    amount: float,
    avg_amount: float,
    velocity: int,
    signals: List[Dict[str, Any]],
) -> List[str]:
    sig = {s["name"]: s["points"] for s in signals}
    evidence: List[str] = []

    if sig.get("Amount anomaly", 0) > 0:
        ratio = amount / max(avg_amount, 1)
        evidence.append(
            f"Transaction amount ({_fmt_money(amount)}) is {ratio:.1f}x this "
            f"customer's typical transaction of {_fmt_money(avg_amount)}"
        )
    if sig.get("Velocity anomaly", 0) > 0:
        evidence.append(f"{velocity} transactions observed within the past hour, above normal velocity")
    if sig.get("Device anomaly", 0) > 0:
        evidence.append("Transaction originated from a device not previously associated with this account")
    if sig.get("Location anomaly", 0) > 0:
        evidence.append("Transaction location differs from the customer's established activity area")
    if sig.get("Beneficiary anomaly", 0) > 0:
        evidence.append("Funds are directed to a beneficiary not seen on this account before")
    if sig.get("Time anomaly", 0) > 0:
        evidence.append("Transaction occurred at an unusual hour relative to this customer's behavior")
    if sig.get("Customer history", 0) > 0:
        evidence.append("Customer profile carries an elevated historical risk rating")

    if not evidence:
        evidence.append("No anomaly signals fired; behavior is consistent with the customer's established profile")

    return evidence


def _template_root_cause(signals: List[Dict[str, Any]]) -> str:
    fired = sorted([s for s in signals if s["points"] > 0], key=lambda s: -s["points"])
    if not fired:
        return "No significant anomaly signals were detected; this transaction matches the customer's normal profile."

    def label(s):
        return s["name"].lower().replace(" anomaly", "").replace("customer history", "risk history")

    if len(fired) >= 2:
        a, b = label(fired[0]), label(fired[1])
        return (
            f"Risk is driven primarily by {a} and {b} signals occurring together. "
            f"That combination is more consistent with account compromise or coordinated fraud "
            f"than with ordinary variation in customer spending, which is why it is treated as "
            f"higher risk than either signal alone would justify."
        )
    else:
        a = label(fired[0])
        return (
            f"Risk is driven primarily by a single {a} signal. On its own this is a moderate "
            f"but not conclusive indicator, so the recommended response is proportionate rather "
            f"than maximal."
        )


def _ai_root_cause(evidence: List[str], fallback: str) -> str:
    """Optional: ask Claude to turn the structured evidence into prose.
    Silently falls back to the deterministic narrative on any failure
    (no key configured, no network, package missing, etc.)."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key or not evidence:
        return fallback
    try:
        import anthropic  # type: ignore

        client = anthropic.Anthropic(api_key=api_key)
        prompt = (
            "You are a fraud/risk investigation assistant. Given this structured "
            "evidence for a single financial transaction, write ONE short paragraph "
            "(2-3 sentences, plain language, no bullet points) explaining the likely "
            "root cause of the risk and why it matters. Do not invent evidence beyond "
            "what is listed.\n\nEvidence:\n- " + "\n- ".join(evidence)
        )
        resp = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=220,
            messages=[{"role": "user", "content": prompt}],
        )
        text = "".join(block.text for block in resp.content if getattr(block, "type", "") == "text").strip()
        return text or fallback
    except Exception:
        return fallback


def investigate(
    amount: float,
    avg_amount: float,
    velocity: int,
    signals: List[Dict[str, Any]],
) -> Tuple[List[str], str]:
    evidence = build_evidence(amount, avg_amount, velocity, signals)
    template = _template_root_cause(signals)
    root_cause = _ai_root_cause(evidence, template)
    return evidence, root_cause
